name: Developer Guide
weight: 10
description: For computer programmers who create and improve functionality within CiviCRM
category: Core
langs:
  en:
    repo: 'https://github.com/civicrm/civicrm-dev-docs'
