name: Developer guide
weight: 10
description: For CiviCRM developers
category: Core
langs:
    en:
        repo: 'https://github.com/civicrm/civicrm-dev-docs'
        latest: master
        stable: master
